// Reading list data. type keys: comp, bench, arch, train, ind, infra, found
// pri: 0 (read first) .. 3 (horizon)
module.exports = [
  // ------------------------------------------------------------------ P0
  {
    id: "R01", pri: 0, type: "comp", mins: 60,
    title: "swegemma Evaluation Harness & Competitor Guide",
    meta: "Competition organizers (Google DeepMind / Kaggle) · Sep 2026 · ships with the competition data",
    url: "https://www.kaggle.com/competitions/gemma-4-developer-agent/data",
    why: "This is the rulebook for everything your agent can see and do: the exact initial prompt, the 9 tool contracts, budgets, the nudge messages, context compaction and the verification procedure.",
    take: "Most early zero scores come from harness mechanics, not model ability: the sample config gives the agent 1 minute and 10 tool calls per task, and a task where the agent never produces a diff cannot score.",
    focus: "§5 interaction protocol, §7 budgets and compaction, §8 verification, §10 gotchas. Re-read after every surprising leaderboard result.",
  },
  {
    id: "R02", pri: 0, type: "comp", mins: 30,
    title: "gemma-swe-agent: a participant's local harness and competition digest",
    meta: "happyc0der · GitHub · Sep 2026 · community code, not official",
    url: "https://github.com/happyc0der/gemma-swe-agent",
    why: "A public re-implementation of the unreleased evaluator (Docker sandboxes, the 9 tools, ADK compile, verification) plus a one-page digest of the rules. It saves you a week of plumbing, or at least shows you what that week involves.",
    take: "Gold patches pass 109/129 tasks locally. The other 20 fail because of environment differences such as network-dependent timeouts and pygments versions, so exclude those tasks from local scoring. On day 1 the top public score was about 0.12.",
    focus: "docs/competition.md, docs/harness-fidelity.md, experiments/. Check the competition's public-sharing rules before reusing any of it.",
  },
  {
    id: "R03", pri: 0, type: "bench", mins: 45,
    title: "SWE-bench: Can Language Models Resolve Real-World GitHub Issues?",
    meta: "Jimenez, Yang, Wettig, Yao, Pei, Press, Narasimhan · ICLR 2024 · arXiv 2310.06770",
    url: "https://arxiv.org/abs/2310.06770",
    why: "The competition's task format (problem statement, base_commit, hidden test_patch, resolved = tests pass) comes directly from SWE-bench, and the private test set was curated the same way.",
    take: "Tasks come from real issue→PR pairs where the PR adds tests that fail before the fix and pass after. The metric is binary, so a near-miss patch scores exactly 0.",
    focus: "§2 benchmark construction, §5 analysis (patch length, files edited). Compare with the public set's median fix: 31 lines in 1 file.",
  },
  {
    id: "R04", pri: 0, type: "arch", mins: 60,
    title: "SWE-agent: Agent-Computer Interfaces Enable Automated Software Engineering",
    meta: "Yang, Jimenez, Wettig, Lieret, Yao, Narasimhan, Press · NeurIPS 2024 · arXiv 2405.15793",
    url: "https://arxiv.org/abs/2405.15793",
    why: "It introduced the agent-computer interface (ACI) and showed that tool design matters as much as the model. Your tools are fixed, but how you teach the model to use them is not.",
    take: "Windowed file views, edit commands with immediate feedback and syntax guards, and concise, informative error messages each produced measurable gains in the ablations. Your prompt has to make up for any of these the fixed tools lack.",
    focus: "§3 ACI design principles and the ablation table. Map each principle to the swegemma tools (read_file = 150-line window, edit_file = 3-tier match).",
  },
  {
    id: "R05", pri: 0, type: "ind", mins: 25,
    title: "Building effective agents",
    meta: "Anthropic Engineering · Dec 2024",
    url: "https://www.anthropic.com/engineering/building-effective-agents",
    why: "It gives the standard vocabulary for workflows versus agents (prompt chaining, routing, parallelization, orchestrator-workers, evaluator-optimizer), and these map 1:1 onto ADK's Sequential, Parallel and Loop agents and AgentTool.",
    take: "Start with the simplest thing that works and add structure only when it measurably helps. Workflows trade flexibility for predictability, and that trade often pays off for weaker models.",
    focus: "The patterns section and the appendix on prompt-engineering your tools.",
  },
  {
    id: "R06", pri: 0, type: "ind", mins: 20,
    title: "Raising the bar on SWE-bench Verified with Claude 3.5 Sonnet",
    meta: "Anthropic Engineering · Jan 2025",
    url: "https://www.anthropic.com/engineering/swe-bench-sonnet",
    why: "It publishes a complete minimal scaffold (one prompt, a bash tool and an edit tool) that reached 49% on Verified. It's the closest public template to a single-LlmAgent submission.",
    take: "The suggested workflow in the prompt was: explore the repo, write a reproduction script, fix, rerun, then think about edge cases. Tool descriptions got as much care as the prompt, and exact-match string replacement was the most reliable edit format.",
    focus: "The full prompt and tool specs. Use them as the starting skeleton for prompts/system.md.",
  },
  {
    id: "R07", pri: 0, type: "arch", mins: 30,
    title: "mini-swe-agent: the 100-line, bash-only SWE agent",
    meta: "SWE-agent team (Princeton & Stanford) · 2025 · open source",
    url: "https://github.com/SWE-agent/mini-swe-agent",
    why: "It's a working agent loop small enough to read in one sitting. Its README reports more than 74% on Verified with frontier models using nothing but bash.",
    take: "Once models got strong, most scaffold complexity stopped paying for itself. The open question for you is where that stops being true for a 31B INT4 model with a 32k window.",
    focus: "The agent loop, the default prompt templates, and how output truncation and step limits are handled.",
  },
  {
    id: "R08", pri: 0, type: "arch", mins: 45,
    title: "Agentless: Demystifying LLM-based Software Engineering Agents",
    meta: "Xia, Deng, Dunn, Zhang · 2024 (FSE 2025) · arXiv 2407.01489",
    url: "https://arxiv.org/abs/2407.01489",
    why: "A fixed localize → repair → validate pipeline with no free-form agent loop. It's the natural template for an ADK SequentialAgent and holds up well with weaker models.",
    take: "Hierarchical localization (file → class/function → edit location), sampling several candidate patches, and choosing among them with generated reproduction tests. It was highly competitive at a fraction of agent cost.",
    focus: "The localization stages and the patch-selection logic. Ask which stages could each be one LlmAgent with an output_key.",
  },
  {
    id: "R09", pri: 0, type: "ind", mins: 25,
    title: "Effective context engineering for AI agents",
    meta: "Anthropic Engineering · Sep 2025",
    url: "https://www.anthropic.com/engineering/effective-context-engineering-for-ai-agents",
    why: "Your hard ceiling is 32,768 tokens for prompt, thinking and output combined, with harness compaction every 15 events. Context is the scarcest resource you have.",
    take: "Treat context as a finite attention budget. Retrieve information just in time, keep structured notes, compact aggressively, and hand exploration to sub-agents that return condensed summaries.",
    focus: "The compaction and sub-agent sections. Design what a localization sub-agent should hand back (file:line list plus a one-paragraph hypothesis).",
  },
  {
    id: "R10", pri: 0, type: "infra", mins: 60,
    title: "Agent Development Kit (ADK) docs: LLM agents, workflow agents, multi-agent systems, skills",
    meta: "Google · 2025–2026 · official documentation",
    url: "https://google.github.io/adk-docs/",
    why: "Your submission is an ADK configuration. Everything architectural you want to try has to be expressed as LlmAgent, SequentialAgent, LoopAgent, ParallelAgent, AgentTool, state and skills.",
    take: "Key mechanics: output_key writes to session state, {var} templating reads from it, include_contents='none' gives a sub-agent a clean context, AgentTool returns a summary, and a LoopAgent needs an escalation or exit condition.",
    focus: "Agents → LLM agents, Workflow agents, Multi-agent; Sessions → State; Skills. Check each feature against the declarative YAML schema in R01 §2.",
  },
  {
    id: "R11", pri: 0, type: "infra", mins: 30,
    title: "Gemma 4 model card and launch post",
    meta: "Google DeepMind · Mar/Apr 2026",
    url: "https://ai.google.dev/gemma/docs/core/model_card_4",
    why: "You need to know the model's native tool-call format, its thinking modes and its published coding results before you tune prompts or train adapters.",
    take: "The 31B dense model has native function calling and configurable thinking. The competition serves the INT4 QAT (W4A16) build, so check any behaviour you rely on against the quantized model, not the bf16 one.",
    focus: "Prompt formatting and tool-use sections, the thinking configuration, and the benchmark table. Also read the launch post: https://blog.google/innovation-and-ai/technology/developers-tools/gemma-4/",
  },

  // ------------------------------------------------------------------ P1
  {
    id: "R12", pri: 1, type: "ind", mins: 25,
    title: "Writing effective tools for agents — with agents",
    meta: "Anthropic Engineering · Sep 2025",
    url: "https://www.anthropic.com/engineering/writing-tools-for-agents",
    why: "The 9 tools are fixed, but sub-agents exposed through AgentTool and skills are tools you design, and their names, descriptions and return formats drive how often and how well the model uses them.",
    take: "Build evaluation tasks, read the transcripts, and iterate on tool descriptions. Return high-signal, token-efficient output and make errors say what to do next.",
    focus: "The evaluation-driven loop for improving tools. Apply it to your sub-agent descriptions and SKILL.md files.",
  },
  {
    id: "R13", pri: 1, type: "ind", mins: 30,
    title: "Unrolling the Codex agent loop",
    meta: "OpenAI (Michael Bolin) · Jan 2026",
    url: "https://openai.com/index/unrolling-the-codex-agent-loop/",
    why: "An inside view of a production coding-agent loop: how each turn's input is assembled, how tool calls and results flow, and how the context is managed over long sessions.",
    take: "Keep the prompt prefix stable so it can be cached, and treat the loop as a pipeline you can inspect. Compare every design choice with swegemma's loop (nudges, compaction, termination).",
    focus: "Turn assembly and context management. Note which choices you can reproduce declaratively and which you can't.",
  },
  {
    id: "R14", pri: 1, type: "arch", mins: 45,
    title: "OpenHands: An Open Platform for AI Software Developers as Generalist Agents (and CodeAct)",
    meta: "Wang et al. · ICLR 2025 · arXiv 2407.16741; CodeAct: arXiv 2402.01030 (ICML 2024)",
    url: "https://arxiv.org/abs/2407.16741",
    why: "OpenHands is the most-used open harness for training and evaluating open coding models; SWE-Gym and Devstral build on it. CodeAct argues for code as the action space.",
    take: "Event-stream architecture, a sandboxed runtime, and agent delegation. Code actions compose better than JSON tool calls, and you can partly approximate them here with run_command running python3 -c.",
    focus: "Architecture section, the CodeActAgent prompt, and the evaluation harness design.",
  },
  {
    id: "R15", pri: 1, type: "train", mins: 45,
    title: "Training Software Engineering Agents and Verifiers with SWE-Gym",
    meta: "Pan, Wang, Neubig, Jaitly, Ji, Suhr, Zhang · ICML 2025 · arXiv 2412.21139",
    url: "https://arxiv.org/abs/2412.21139",
    why: "The first open environment of real, executable SWE tasks built for training. It shows that fine-tuning on a few hundred successful agent trajectories lifts a 32B model, and that trained verifiers make best-of-n selection work.",
    take: "Rejection-sampling fine-tuning (keep only trajectories that pass the tests) works with small data. The same recipe fits your 129 tasks plus synthetic ones, using Gemma's own successful runs.",
    focus: "The trajectory collection and filtering recipe, the scaling curves, and the verifier section.",
  },
  {
    id: "R16", pri: 1, type: "train", mins: 45,
    title: "SWE-smith: Scaling Data for Software Engineering Agents",
    meta: "Yang et al. · 2025 (NeurIPS D&B) · arXiv 2504.21798",
    url: "https://arxiv.org/abs/2504.21798",
    why: "It creates task instances by injecting bugs into any Python repository that has tests, which is how you get beyond 129 training tasks, including tasks from repos that resemble the hidden ones.",
    take: "Around 50k synthetic instances from 128 repos and about 5k expert trajectories trained SWE-agent-LM-32B to roughly 40% on Verified. Diversity across repos mattered.",
    focus: "The bug-synthesis strategies (LM rewrite, AST mutation, PR inversion), the validation step, and the data-scaling ablations.",
  },
  {
    id: "R17", pri: 1, type: "train", mins: 45,
    title: "R2E-Gym: Procedural Environments and Hybrid Verifiers for Scaling Open-Weights SWE Agents",
    meta: "Jain et al. · COLM 2025 · arXiv 2504.07164",
    url: "https://arxiv.org/abs/2504.07164",
    why: "It builds executable environments from commits, the same curation idea as this competition's dataset, and combines execution-based and execution-free verifiers for selecting patches.",
    take: "Open-weight agents reached 51% on Verified with hybrid test-time verification. Execution-based and execution-free verifiers fail in different ways, so combining them helps.",
    focus: "The SWE-Gen commit-to-environment pipeline and the hybrid verifier results.",
  },
  {
    id: "R18", pri: 1, type: "train", mins: 40,
    title: "SWE-RL: Advancing LLM Reasoning via Reinforcement Learning on Open Software Evolution",
    meta: "Wei et al. (Meta) · 2025 (NeurIPS 2025) · arXiv 2502.18449",
    url: "https://arxiv.org/abs/2502.18449",
    why: "RL with a cheap, rule-based reward (similarity to the reference patch) over large software-evolution data, with no execution needed. That makes it feasible on free-tier GPUs, where execution-based RL isn't.",
    take: "Llama3-SWE-RL-70B reached 41.0% on Verified, and the RL also improved out-of-domain reasoning.",
    focus: "Reward design and data curation. Think about how patch-similarity reward could bootstrap before execution-based reward.",
  },
  {
    id: "R19", pri: 1, type: "train", mins: 30,
    title: "DeepSWE: training a fully open-source SWE agent by scaling RL",
    meta: "Agentica × Together AI · Jul 2025 · blog + open weights and code",
    url: "https://www.together.ai/blog/deepswe",
    why: "An RL-only recipe on a 32B open model (Qwen3-32B) using R2E-Gym environments. The post is candid about which training tricks mattered.",
    take: "Pass@1 was around 42% on Verified, rising to about 59% with test-time scaling. Filtering tasks for learnability and keeping RL stable were the hard parts.",
    focus: "The ablations and the test-time scaling section. Estimate what fraction of this is reachable with LoRA and Kaggle GPUs.",
  },
  {
    id: "R20", pri: 1, type: "train", mins: 40,
    title: "Kimi-Dev: Agentless Training as Skill Prior for SWE-Agents",
    meta: "Moonshot AI · Sep 2025 · arXiv 2509.23045",
    url: "https://arxiv.org/abs/2509.23045",
    why: "It connects the two architecture families: train structured agentless skills (localize, edit, self-verify) first, then adapt briefly to free-form agent mode.",
    take: "60.4% on Verified as an agentless workflow, and 48.6% as an agent after SFT on about 5k public trajectories. Skill priors transfer to agent behaviour.",
    focus: "The staged training recipe. It suggests a two-adapter design: a localize/patch skill LoRA plus an agent-mode LoRA.",
  },
  {
    id: "R21", pri: 1, type: "train", mins: 40,
    title: "SWE-Protégé: Learning to Selectively Collaborate With an Expert Unlocks Small Language Models as SWE Agents",
    meta: "2026 (Feb) · arXiv 2602.22124",
    url: "https://arxiv.org/abs/2602.22124",
    why: "It names the main way small models fail on SWE tasks, action looping, and trains it away with SFT plus RL that penalises degenerate loops and unproductive steps.",
    take: "Qwen2.5-Coder-7B reached 42.4% on Verified while calling the expert only about 4 times per task. You can't call an expert offline, but stall detection and anti-loop reward shaping carry over.",
    focus: "The looping analysis and the reward terms. Measure looping rates in your own trajectories first.",
  },
  {
    id: "R22", pri: 1, type: "train", mins: 40,
    title: "Explore More, Drift Less: Outcome-Only RL Can Suffice for Long-Horizon Interactive Agents",
    meta: "2026 (Sep) · arXiv 2609.01245",
    url: "https://arxiv.org/abs/2609.01245",
    why: "It diagnoses the two failure modes you'd hit doing RL on 129 tasks: signal starvation (all-pass or all-fail groups give no gradient) and policy drift from many updates on a small pool.",
    take: "The CANOPY recipe (explore more, drift less) took a Qwen3-14B policy to the top of AppWorld and improved Qwen3.5-9B by 16.6 points on SWE-bench Verified.",
    focus: "The diagnosis sections. Even if you never run RL, it explains why naive GRPO on small task pools stalls.",
  },
  {
    id: "R23", pri: 1, type: "infra", mins: 45,
    title: "LoRA (2021) and QLoRA (2023): low-rank adaptation and fine-tuning on quantized bases",
    meta: "Hu et al., arXiv 2106.09685 · Dettmers et al., NeurIPS 2023, arXiv 2305.14314",
    url: "https://arxiv.org/abs/2305.14314",
    why: "LoRA adapters are the only way to ship weight changes: PEFT safetensors, rank ≤ 128, at most 8 adapters, under 3 GiB in total, served on an INT4 base.",
    take: "Choose target modules and rank to fit your data size, and train on the quantized base you'll be served on, because a train/serve mismatch costs accuracy. A community report says high-rank, all-layer LoRA on this W4A16 build was unstable in vLLM, so run a small smoke test before any long training job.",
    focus: "LoRA §4 on which matrices to adapt and QLoRA §3–4 on double quantization and paged optimizers. See also 'LoRA Learns Less and Forgets Less' (arXiv 2405.09673).",
  },
  {
    id: "R24", pri: 1, type: "bench", mins: 20,
    title: "Introducing SWE-bench Verified",
    meta: "OpenAI · Aug 2024",
    url: "https://openai.com/index/introducing-swe-bench-verified/",
    why: "It explains why many raw SWE-bench tasks are unfair (underspecified issues, tests that check one specific implementation), which helps you judge what an unsolvable hidden task looks like.",
    take: "Human annotators filtered to 500 well-specified, fairly tested tasks. Expect some hidden tasks to be effectively unsolvable, and don't burn budget on them.",
    focus: "The annotation criteria. Use them to label your own failures as model error or task ambiguity.",
  },

  // ------------------------------------------------------------------ P2
  {
    id: "R25", pri: 2, type: "found", mins: 30,
    title: "ReAct: Synergizing Reasoning and Acting in Language Models",
    meta: "Yao et al. · ICLR 2023 · arXiv 2210.03629",
    url: "https://arxiv.org/abs/2210.03629",
    why: "The thought → action → observation loop that every tool-using agent, including swegemma's LlmAgent loop, descends from.",
    take: "Interleaving reasoning with actions grounds the reasoning in observations. The modern version is thinking tokens plus native function calls.",
    focus: "The framing and the failure analysis. Skim the experiments.",
  },
  {
    id: "R26", pri: 2, type: "found", mins: 30,
    title: "Reflexion: Language Agents with Verbal Reinforcement Learning",
    meta: "Shinn et al. · NeurIPS 2023 · arXiv 2303.11366",
    url: "https://arxiv.org/abs/2303.11366",
    why: "It's the basis for a verify-then-retry loop in which a failed attempt produces a written critique that the next attempt reads.",
    take: "Self-reflection stored in memory improves retries when there's a reliable feedback signal. Here that signal is your reproduction script's result.",
    focus: "The reflection-memory mechanism. Map it onto a LoopAgent with output_key='critique'.",
  },
  {
    id: "R27", pri: 2, type: "arch", mins: 35,
    title: "AutoCodeRover: Autonomous Program Improvement",
    meta: "Zhang, Ruan, Fan, Roychoudhury · ISSTA 2024 · arXiv 2404.05427",
    url: "https://arxiv.org/abs/2404.05427",
    why: "Program-structure-aware code search (class and method APIs over the AST) is the closest published analogue to the competition's graph tools (get_code_neighbors and the others).",
    take: "Structured search beats grep for localization when the model knows which symbol to ask for. Spectrum-based fault localization helps when tests exist.",
    focus: "The search APIs and the context-retrieval stage. Compare them with swegemma's 4-tier symbol resolution.",
  },
  {
    id: "R28", pri: 2, type: "arch", mins: 40,
    title: "CodeMonkeys: Scaling Test-Time Compute for Software Engineering",
    meta: "Ehrlich et al. (Stanford) · 2025 · arXiv 2501.14723",
    url: "https://arxiv.org/abs/2501.14723",
    why: "It addresses how to spend a fixed compute budget: several parallel attempts, each iterating serially, then a selection step. You have a fixed 12-hour budget for about 120 tasks.",
    take: "Coverage (at least one correct candidate) grows with samples, but selection becomes the bottleneck. Generated tests plus model-based selection closed much of the gap.",
    focus: "The serial versus parallel scaling curves. Estimate how many attempts fit in your per-task time budget.",
  },
  {
    id: "R29", pri: 2, type: "arch", mins: 35,
    title: "SWE-Search: Monte Carlo Tree Search for Software Agents",
    meta: "Antoniades et al. · ICLR 2025 · arXiv 2410.20285",
    url: "https://arxiv.org/abs/2410.20285",
    why: "Search over agent trajectories with value feedback and backtracking, an alternative to linear retries.",
    take: "MCTS plus a value agent gives relative gains over linear agents, at the cost of more compute per task.",
    focus: "The value-function prompting. It's probably too expensive for a 12-hour cap, but useful for the paper track's related work.",
  },
  {
    id: "R30", pri: 2, type: "train", mins: 35,
    title: "SWE-RM: Execution-Free Feedback for Software Engineering Agents",
    meta: "Dec 2025 · arXiv 2512.21919",
    url: "https://arxiv.org/abs/2512.21919",
    why: "Reward models that score patches or trajectories without running tests could become a LoRA 'judge' sub-agent that picks among candidate patches.",
    take: "Execution-free reward models can guide selection and RL when execution is expensive. Check how well they're calibrated on unseen repos.",
    focus: "The results on unseen repositories and the model sizes. Decide whether a judge LoRA is worth one of your 8 adapter slots.",
  },
  {
    id: "R31", pri: 2, type: "train", mins: 40,
    title: "Training Long-Context, Multi-Turn Software Engineering Agents with Reinforcement Learning",
    meta: "Aug 2025 · arXiv 2508.03501",
    url: "https://arxiv.org/abs/2508.03501",
    why: "A practical recipe of rejection fine-tuning followed by DAPO-style RL for long, multi-turn SWE trajectories on an open model.",
    take: "A 72B open model went from 11% to 39% pass@1 on Verified, with the gains split between the RFT stage and the RL stage.",
    focus: "The RFT stage, the part that's feasible for you, and the tricks for handling long context during training.",
  },
  {
    id: "R32", pri: 2, type: "train", mins: 30,
    title: "Open-SWE-Traces: Dual-Mode Multilingual Distillation for SWE Agents",
    meta: "NVIDIA · Jun 2026 · arXiv 2606.16038 · Hugging Face collection nvidia/open-swe-traces",
    url: "https://huggingface.co/papers/2606.16038",
    why: "About 207k agent trajectories in both thinking and non-thinking modes, a candidate source of SFT data (the Python subset) if the competition rules allow it.",
    take: "Their best model scores 61.7% on Verified. Thinking and non-thinking traces serve different uses, and multilingual data helped on the multilingual benchmarks.",
    focus: "Check the licence, whether the data counts as 'freely accessible', and how much conversion to the 9-tool schema would be needed.",
  },
  {
    id: "R33", pri: 2, type: "train", mins: 30,
    title: "SWE-Dev: Building Software Engineering Agents with Training and Inference Scaling",
    meta: "2025 · arXiv 2506.07636",
    url: "https://arxiv.org/abs/2506.07636",
    why: "Another open recipe that pairs trajectory SFT with inference-time scaling, and includes test-case synthesis for training tasks.",
    take: "Training scaling and inference scaling add up. Synthesised tests widen the pool of trainable tasks.",
    focus: "The test-synthesis pipeline, which you could reuse to create reproduction tests for extra training tasks.",
  },
  {
    id: "R34", pri: 2, type: "ind", mins: 20,
    title: "Claude Code: best practices for agentic coding",
    meta: "Anthropic Engineering · Apr 2025",
    url: "https://www.anthropic.com/engineering/claude-code-best-practices",
    why: "Field-tested workflows (explore → plan → code → commit, test-driven loops, course-correcting early) that you can write into system prompts and skills.",
    take: "Asking for a plan before editing and giving the agent a verification target, such as a test or reproduction, both substantially improve results.",
    focus: "The workflow recipes. Turn two of them into prompt variants and A/B test them.",
  },
  {
    id: "R35", pri: 2, type: "ind", mins: 20,
    title: "Equipping agents for the real world with Agent Skills",
    meta: "Anthropic Engineering · Oct 2025",
    url: "https://www.anthropic.com/engineering/equipping-agents-for-the-real-world-with-agent-skills",
    why: "Submissions support skills/<name>/SKILL.md with scripts that run in the sandbox. Progressive disclosure keeps them from costing context until they're needed.",
    take: "A skill is a folder of instructions, scripts and resources that loads only when it's relevant, which suits a 32k window. Candidate skills: repo-mapping, repro-test scaffold, diff sanity check.",
    focus: "Progressive disclosure design. Note that every skill script run debits your tool-call budget.",
  },
  {
    id: "R36", pri: 2, type: "ind", mins: 20,
    title: "Effective harnesses for long-running agents",
    meta: "Anthropic Engineering · Nov 2025",
    url: "https://www.anthropic.com/engineering/effective-harnesses-for-long-running-agents",
    why: "It covers how an agent keeps making progress across context resets, which applies directly to you because swegemma compacts history every 15 events.",
    take: "Keep an explicit progress file, work in small increments, and verify each one. A notes file in /tmp can survive compaction when the conversation history doesn't.",
    focus: "The progress-file pattern and the initializer/worker split.",
  },
  {
    id: "R37", pri: 2, type: "ind", mins: 25,
    title: "Introducing Codex, and the GPT-5-Codex upgrade",
    meta: "OpenAI · May 2025 and Sep 2025",
    url: "https://openai.com/index/introducing-codex/",
    why: "A coding model trained with RL to work in a sandbox, run tests and cite evidence. It shows what 'train the model for the harness' looks like at the frontier.",
    take: "The model was trained on real tasks inside the harness it's deployed in, adjusts how long it thinks to task difficulty, and follows repository instructions (AGENTS.md).",
    focus: "The training-environment description, and the idea of adaptive effort under a time budget.",
  },
  {
    id: "R38", pri: 2, type: "bench", mins: 25,
    title: "Does SWE-Bench-Verified Test Agent Ability or Model Memory?",
    meta: "Dec 2025 · arXiv 2512.10218",
    url: "https://arxiv.org/abs/2512.10218",
    why: "Contamination is why the organizers test on private repos. It's also a warning not to read much into scores on fastapi, rich or requests, which the model has probably memorised.",
    take: "Public benchmark scores partly reflect memorisation of popular repos, so generalisation to unseen code is the real test.",
    focus: "The methodology. Apply the same scepticism to your local scores and hold out whole repos.",
  },
  {
    id: "R39", pri: 2, type: "bench", mins: 30,
    title: "SWE-bench Pro and SWE-rebench: harder, fresher, contamination-resistant tasks",
    meta: "Scale AI · Sep 2025 · arXiv 2509.16941  |  Nebius · 2025 · arXiv 2505.20411",
    url: "https://arxiv.org/abs/2505.20411",
    why: "SWE-rebench's automated, continually refreshed curation mirrors the competition's commit-mining pipeline. SWE-bench Pro adds harder tasks, including from private codebases.",
    take: "Both are possible sources of extra Python training and evaluation tasks. Check their licences and the competition's external-data rule first.",
    focus: "The curation pipelines and task filters, and how they define 'solvable'.",
  },
  {
    id: "R40", pri: 2, type: "infra", mins: 30,
    title: "vLLM (PagedAttention) and S-LoRA: how your model is actually served",
    meta: "Kwon et al., SOSP 2023, arXiv 2309.06180 · Sheng et al., MLSys 2024, arXiv 2311.03285",
    url: "https://arxiv.org/abs/2309.06180",
    why: "KV-cache management and prefix caching explain why a stable prompt prefix is cheap and why concurrent sessions compete for memory. S-LoRA explains the cost of multi-adapter serving.",
    take: "Keep system prompts identical across tasks so the prefix is cached, keep adapters few and low-rank, and remember that thinking tokens take up KV cache like any other tokens.",
    focus: "The PagedAttention design and the S-LoRA batching. Skip the kernel details.",
  },

  // ------------------------------------------------------------------ P3 (compact)
  {
    id: "R41", pri: 3, type: "ind", mins: 20,
    title: "Harness engineering: leveraging Codex in an agent-first world",
    meta: "OpenAI · Feb 2026", url: "https://openai.com/index/harness-engineering/",
    why: "How engineering norms change when agents write all the code: the repo and its tests become the agent's interface.",
  },
  {
    id: "R42", pri: 3, type: "ind", mins: 20,
    title: "Harness design for long-running application development",
    meta: "Anthropic Engineering · Mar 2026", url: "https://www.anthropic.com/engineering/harness-design-long-running-apps",
    why: "How much performance at the frontier comes from harness design, with generator/evaluator splits.",
  },
  {
    id: "R43", pri: 3, type: "ind", mins: 20,
    title: "Scaling Managed Agents: decoupling the brain from the hands",
    meta: "Anthropic Engineering · Apr 2026", url: "https://www.anthropic.com/engineering/managed-agents",
    why: "Argues that harnesses encode assumptions that go stale as models improve. Worth keeping in mind before over-engineering yours.",
  },
  {
    id: "R44", pri: 3, type: "ind", mins: 25,
    title: "Demystifying evals for AI agents",
    meta: "Anthropic Engineering · Jan 2026", url: "https://www.anthropic.com/engineering/demystifying-evals-for-ai-agents",
    why: "Grader design and transcript review, useful for building your local eval loop and failure taxonomy.",
  },
  {
    id: "R45", pri: 3, type: "ind", mins: 20,
    title: "Building a C compiler with a team of parallel Claudes",
    meta: "Anthropic Engineering · 2026", url: "https://www.anthropic.com/engineering/building-c-compiler",
    why: "A case study of test suites as the steering signal for many parallel agents.",
  },
  {
    id: "R46", pri: 3, type: "train", mins: 30,
    title: "Devstral and Qwen3-Coder: how open labs post-train agentic coders",
    meta: "Mistral AI × All Hands AI, May 2025 · Qwen team, Jul 2025", url: "https://mistral.ai/news/devstral",
    why: "Launch posts describing large-scale agent RL on SWE environments. Qwen3-Coder: https://qwenlm.github.io/blog/qwen3-coder/",
  },
  {
    id: "R47", pri: 3, type: "bench", mins: 20,
    title: "SWE-ABS: adversarial benchmark strengthening exposes inflated success rates",
    meta: "2026 · arXiv 2603.00520", url: "https://arxiv.org/abs/2603.00520",
    why: "Weak tests accept wrong patches. The hidden tests may be stricter than your reproduction script.",
  },
  {
    id: "R48", pri: 3, type: "arch", mins: 30,
    title: "Gemini CLI (open source)",
    meta: "Google · Jun 2025 · GitHub", url: "https://github.com/google-gemini/gemini-cli",
    why: "Google's own prompts and tool design for Gemini-family agents. Read the system prompt and edit tool.",
  },
  {
    id: "R49", pri: 3, type: "found", mins: 20,
    title: "Evaluating Large Language Models Trained on Code (Codex / HumanEval)",
    meta: "Chen et al. · 2021 · arXiv 2107.03374", url: "https://arxiv.org/abs/2107.03374",
    why: "Where it started: function-level benchmarks and the pass@k metric.",
  },
  {
    id: "R50", pri: 3, type: "found", mins: 60,
    title: "From Code Foundation Models to Agents and Applications (survey)",
    meta: "Nov 2025 · arXiv 2511.18538", url: "https://arxiv.org/abs/2511.18538",
    why: "A broad survey to consult when writing related work for the paper track, rather than one to read cover to cover.",
  },
];
